[package]
name = "val-rs"
version = "0.1.0"
authors = ["mike"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
valico = "3.4.0"